ALTER TABLE `#__tj_certificate_templates` CHANGE `title` `title` varchar(150) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_templates` CHANGE `unique_code` `unique_code` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_templates` CHANGE `body` `body` text DEFAULT NULL;
ALTER TABLE `#__tj_certificate_templates` CHANGE `template_css` `template_css` text DEFAULT NULL;
ALTER TABLE `#__tj_certificate_templates` CHANGE `client` `client` varchar(100) NOT NULL DEFAULT '' COMMENT 'e.g. com_jticketing.event, com_tjlms.course';
ALTER TABLE `#__tj_certificate_templates` CHANGE `ordering` `ordering` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_templates` CHANGE `state` `state` tinyint(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_templates` CHANGE `checked_out` `checked_out` int(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_templates` CHANGE `checked_out_time` `checked_out_time` datetime DEFAULT NULL;
ALTER TABLE `#__tj_certificate_templates` CHANGE `created_by` `created_by` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_templates` CHANGE `created_on` `created_on` datetime DEFAULT NULL;
ALTER TABLE `#__tj_certificate_templates` CHANGE `modified_by` `modified_by` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_templates` CHANGE `modified_on` `modified_on` datetime DEFAULT NULL;
ALTER TABLE `#__tj_certificate_templates` CHANGE `is_public` `is_public` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1-Private, 2-Public';
ALTER TABLE `#__tj_certificate_templates` CHANGE `params` `params` text DEFAULT NULL;

ALTER TABLE `#__tj_certificate_issue` CHANGE `unique_certificate_id` `unique_certificate_id` varchar(150) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_issue` CHANGE `certificate_template_id` `certificate_template_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `generated_body` `generated_body` text DEFAULT NULL;
ALTER TABLE `#__tj_certificate_issue` CHANGE `client` `client` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_issue` CHANGE `client_id` `client_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `client_issued_to` `client_issued_to` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `client_issued_to_name` `client_issued_to_name` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_issue` CHANGE `user_id` `user_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `comment` `comment` text DEFAULT NULL;
ALTER TABLE `#__tj_certificate_issue` CHANGE `state` `state` tinyint(3) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `issued_on` `issued_on` datetime DEFAULT NULL;
ALTER TABLE `#__tj_certificate_issue` CHANGE `expired_on` `expired_on` datetime DEFAULT NULL;
ALTER TABLE `#__tj_certificate_issue` CHANGE `is_external` `is_external` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_issue` CHANGE `issuing_org` `issuing_org` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_issue` CHANGE `cert_url` `cert_url` text DEFAULT NULL;
ALTER TABLE `#__tj_certificate_issue` CHANGE `cert_file` `cert_file` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_certificate_issue` CHANGE `created_by` `created_by` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `access` `access` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_certificate_issue` CHANGE `status` `status` varchar(64) NOT NULL DEFAULT '';

ALTER TABLE `#__tj_media_files` CHANGE `title` `title` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `type` `type` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `path` `path` varchar(250) COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `state` `state` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `source` `source` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `original_filename` `original_filename` varchar(250) COLLATE utf8mb4_bin NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `size` `size` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `storage` `storage` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files` CHANGE `created_by` `created_by` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `access` `access` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files` CHANGE `created_date` `created_date` datetime DEFAULT NULL;
ALTER TABLE `#__tj_media_files` CHANGE `params` `params` text DEFAULT NULL;

ALTER TABLE `#__tj_media_files_xref` CHANGE `media_id` `media_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files_xref` CHANGE `client_id` `client_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__tj_media_files_xref` CHANGE `client` `client` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `#__tj_media_files_xref` CHANGE `is_gallery` `is_gallery` tinyint(1) NOT NULL DEFAULT 0;
